export enum ConsumerType {
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  EXPIRE_TOKENS = 'EXPIRE_TOKENS',
  ACTIVE_QUEUE_TOKEN = 'ACTIVE_QUEUE_TOKEN',
}

export enum ConsumerGroup {
  PAYMENT_COMPLETED_HANDLER_GROUP = 'PAYMENT_COMPLETED_HANDLER_GROUP',
  EXPIRE_TOKEN_HANDLER_GROUP = 'EXPIRE_TOKENS_HANDLER_GROUP',
  ACTIVE_QUEUE_TOKEN_HANDLER_GROUP = 'ACTIVE_QUEUE_TOKEN_HANDLER_GROUP',
}

export enum OutboxMarkerGroup {
  PAYMENT_COMPLETED_OUTBOX_MARKER_GROUP = 'PAYMENT_COMPLETED_OUTBOX_MARKER_GROUP',
  EXPIRE_TOKEN_OUTBOX_MARKER_GROUP = 'EXPIRE_TOKENS_OUTBOX_MARKER_GROUP',
  ACTIVE_QUEUE_TOKEN_OUTBOX_MARKER_GROUP = 'ACTIVE_QUEUE_TOKEN_OUTBOX_MARKER_GROUP',
}
