export enum ConsumerType {
  RESERVATION_SEAT = 'reservation-seat',
  RESERVATIONS_EXPIRED = 'expired-reservations',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}

export enum ConsumerGroup {
  RESERVATION_SEAT_HANDLER_GROUP = 'reservation-seat-handler-group',
  PAYMENT_FAILED_HANDLER_GROUP = 'PAYMENT_FAILED_HANDLER_GROUP',
  RESERVATION_EXPIRE_HANDLER_GROUP = 'RESERVATION_EXPIRE_HANDLER_GROUP',
}

export enum OutboxMarkerGroup {
  RESERVATION_SEAT_OUTBOX_MARKER_GROUP = 'reservation-seat-outbox-marker-group',
  PAYMENT_FAILED_OUTBOX_MARKER_GROUP = 'PAYMENT_FAILED_OUTBOX_MARKER_GROUP',
  RESERVATION_EXPIRE_OUTBOX_MARKER_GROUP = 'RESERVATION_EXPIRE_OUTBOX_MARKER_GROUP',
}
