export enum ConsumerType {
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT = 'PAYMENT',
  COMPLETE_RESERVATION_FAILED = 'complete-reservation-failed',
}

export enum ConsumerGroup {
  PAYMENT_FAILED_HANDLER_GROUP = 'PAYMENT_FAILED_HANDLER_GROUP',
  PAYMENT_HANDLER_GROUP = 'PAYMENT_HANDLER_GROUP',
  COMPLETE_RESERVATION_FAILED_HANDLER_GROUP = 'COMPLETE_RESERVATION_FAILED_HANDLER_GROUP',
}

export enum OutboxMarkerGroup {
  PAYMENT_FAILED_OUTBOX_MARKER_GROUP = 'PAYMENT_FAILED_OUTBOX_MARKER_GROUP',
  PAYMENT_OUTBOX_MARKER_GROUP = 'PAYMENT_OUTBOX_MARKER_GROUP',
  COMPLETE_RESERVATION_FAILED_OUTBOX_MARKER_GROUP = 'COMPLETE_RESERVATION_FAILED_OUTBOX_MARKER_GROUP',
}
